export const MODULE_ORDERS = {
    "Striver A2Z": [
      "Learn the Basics",
      "Learn Important Sorting Techniques",
      "Arrays",
      "Binary Search",
      "Strings",
      "Linked List",
      "Recursion & Backtracking",
      "Bit Manipulation",
      "Stack & Queue",
      "Sliding Window & Two Pointers",
      "Heaps",
      "Greedy Algorithms",
      "Binary Trees",
      "Binary Search Trees",
      "Graphs",
      "Dynamic Programming",
      "Tries",
      "Strings [Hard]",
    ],

    "Blind 75": [
      "Array",
      "String",
      "Linked List",
      "Binary",
      "Interval",
      "Matrix",
      "Tree",
      "Heap",
      "Backtracking",
      "Graph",
      "Dynamic Programming",
    ],
  };